### ISSUE TITLE
Reconsider how vectors get added/subtracted to/from numbers

### ISSUE THREAD

**Issue by TodePond** [MaxBittker/sand-blocks#20]
Maybe it could change magnitude instead.

Food for thought: https://youtu.be/h3FndHTu_7M

**Comment by MaxBittker** [comment]
maybe it could rotate them like a clock..

**Comment by TodePond** [comment]
Adding and subtracting turns vectors 45 degrees like a clock now 097609f2ef8bf9320fd5992ee5c95cf6f10d8fd0
