### ISSUE TITLE
storing vectors in registers 

### ISSUE THREAD

**Issue by MaxBittker** [MaxBittker/sand-blocks#31]

**Comment by MaxBittker** [comment]
this is helpful for stuff like rocket or "gliders"

**Comment by TodePond** [comment]
Potentially replaced by the clock vector rotation thing (implemented) and auto-casting numbers to vectors (not implemented yet)

**Comment by TodePond** [comment]
Actually I still think it would be good to implement this. 

It feels great being able to do this with cloner:
![image](https://user-images.githubusercontent.com/15892272/164696163-776adfa0-5b6b-40cc-b6cf-7c7b6ed81917.png)

And I think it would feel great to just store a vector without thinking about it too!
