### ISSUE TITLE
rename elements 

### ISSUE THREAD

**Issue by MaxBittker** [MaxBittker/sand-blocks#40]

**Comment by TodePond** [comment]
Currently working on this on the `rename-elements` branch: https://github.com/MaxBittker/sand-blocks/compare/rename-elements?expand=1

**Comment by TodePond** [comment]
What still needs doing:

- [ ] `element_literal` blocks of the current workspace need to update whenever the validator of `sand_behavior_base` happens. Currently, they only update after the workspace reloads (by selecting another element).
- [ ] The `ElementButton`s only update after clicking on them. They should update as soon as the validator of `sand_behavior_base` happens.
- [ ] The field values of the `element_literal` block rely on the name of each element. So if you change a name, it loses its value. It should use the ID number of the element instead.
- [ ] All starter blocks will need remaking!

**Comment by TodePond** [comment]
`element_literal` blocks now immediately update when you rename an element

**Comment by TodePond** [comment]
Crossed out items on the todo list are now covered by #45
